FROM node:20-alpine

WORKDIR /app

# Install package dependencies
COPY frontend/package*.json ./
RUN npm install

# Copy application source code
COPY frontend/ .

EXPOSE 5173

CMD ["npm", "run", "dev", "--", "--host"]
